# Generated by Django 3.1.5 on 2021-01-15 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('address', models.TextField(max_length=60, null=True)),
                ('dob', models.DateField(null=True)),
                ('company', models.TextField(max_length=40, null=True)),
                ('mobile', models.TextField(max_length=10, null=True)),
                ('city', models.TextField(max_length=10, null=True)),
                ('Status_Choice', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active', max_length=10, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
