# Generated by Django 3.1.5 on 2021-01-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_auto_20210115_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='manager_id',
        ),
    ]
