# Generated by Django 3.1.5 on 2021-01-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20210116_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Status_Choice',
            new_name='Status',
        ),
    ]
