# Generated by Django 3.1.5 on 2021-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='Status_Choice',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
    ]
