# Generated by Django 3.1.5 on 2021-01-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20210115_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
    ]
