# Generated by Django 3.1.5 on 2021-01-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_auto_20210115_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
