# Generated by Django 3.1.5 on 2021-01-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_auto_20210115_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Status_Choice',
            new_name='status_Choice',
        ),
    ]
