# Generated by Django 3.1.5 on 2021-01-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_auto_20210115_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='status_Choice',
        ),
    ]
